name: PR checks

on:
  workflow_dispatch:
  push:
    branches:
      - $default-branch
  pull_request:

jobs:
  test:
    name: fmt, clippy, test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - uses: actions-rust-lang/rustfmt@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - run: cargo build --tests
      - run: cargo test --all-features
